### ISSUE TITLE
Had some issue regarding lens. will checkem later

### ISSUE THREAD

**Issue by tx-qi** [ahmad4fifz/twitter-sentiment#7]
![image](https://user-images.githubusercontent.com/19251969/151730010-ff9ef5f8-da33-4589-8df5-04af2199554d.png)

**Comment by ahmad4fifz** [comment]
baru jadi ke tu mr taqi?

**Comment by tx-qi** [comment]
yes sir afif, but seldomly crashed

**Comment by tx-qi** [comment]
[AetherPrior:normalize-fix](https://github.com/huseinzol05/malaya/pull/108) 

Same issue, regarding the package itself, not in our source code
